name: Build n8n Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -f docker/dockerfiles/Dockerfile -t n8n:custom .

      - name: Save image
        run: |
          docker save n8n:custom | gzip > n8n.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: n8n-docker-image
          path: n8n.tar.gz
