name: 构建Docker镜像

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Build docker image
        run: |
          export NODE_OPTIONS="--max-old-space-size=6144"
          npm i -g pnpm
          pnpm i
          pnpm build:docker

      - name: Save image
        run: |
          docker save n8nio/n8n:local | gzip > n8n.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: n8n
          path: n8n.tar.gz
