name: build-n8n

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Build docker image
        run: pnpm build:docker

      - name: Save image
        run: |
          docker save n8n:latest | gzip > n8n.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: n8n-image
          path: n8n.tar.gz
